[tox]
envlist = py312-django{42,52}, quality
requires = tox-uv>=1

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
commands =
    flake8 crowdsourcehinter/

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    django42: django42
    django52: test
commands = pytest {posargs}
